djebbz_hello:
    pattern:  /hello/{name}
    defaults: { _controller: DjebbZHelloBundle:Default:index }

    pattern: /request.json
    defaults: { _controller: DjebbZHelloBundle:Default:indexJson }
