djebb_z_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DjebbZHelloBundle:Default:index }

    pattern: /{name}.json
    defaults: { _controller: DjebbZHelloBundle:Default:indexJson }
