djebbz_ticket_homepage:
    path:  /home
    defaults: { _controller: DjebbzTicketBundle:Default:index }

djebbz_ticket_login:
    path: /login
    defaults: { _controller: DjebbzTicketBundle:Default:login }

djebbz_ticket_logout:
    pattern:   /logout
    defaults:  { _controller: DjebbzTicketBundle:Default:logout }

djebbz_ticket_tickets:
    pattern:   /tickets
    defaults:  { _controller: DjebbzTicketBundle:Default:showAllTickets }

djebbz_ticket_ticket:
    pattern:   /ticket/{id}
    defaults:  { _controller: DjebbzTicketBundle:Default:showTicket }

djebbz_ticket_ticket_add:
    pattern:   /ticket/add
    defaults:  { _controller: DjebbzTicketBundle:Default:addTicketForm }
    methods:    [GET]

djebbz_ticket_ticket_add:
    pattern:   /ticket/add
    defaults:  { _controller: DjebbzTicketBundle:Default:addTicket }
    methods:    [POST]
